// LOCATIONS
export const GET_ALL_LOCATIONS = 'GET_ALL_LOCATIONS';
export const GET_LOCATION_BY_ID = 'GET_LOCATION_BY_ID';
export const CLEAR_LOCATION = 'CLEAR_LOCATION';

// MENU
export const GET_ALL_MENUS = 'GET_ALL_MENUS';
